### ISSUE TITLE
Correcciones TP3

### ISSUE THREAD

**Issue by mbuchwald** [astrocinco/2c2023-TDA-TP3#8]
Hola! Les dejo yo las correcciones porque Marcos nos avisó que estaba un tanto complicado. 

* Tuve que modificar a mano los scripts para poder ejecutar algunas pruebas. A nivel programa no está nada bueno. Con poner qué scripts correr en el README, y que reciban por parámetro el archivo de entrada, habría sido suficiente. 
* Con un set nuestro de 200 elementos (que demanda más procesamiento que el de 200 que les dimos) les tarda bastante (debería tomar unos pocos segudos, pero tomó 2 minutos). Igual está pasable. 
* La demostración que el problema es NP-Completo es insuficiente. Tuvieron en cuenta únicamente el caso de tener variables, sin complementos. Ese caso particular de SAT se resuelve en O(1) con un simple `return True` (todas las variables en 1 seguro resuelve). Tienen que considerar los complementos. 
* En la solución de BT no consideran que el conjunto ya está cubierto (es decir, que alguno de los jugadores del conjunto ya esté entre los convocados). Pusieron un `n_minimo = 100` cuando podrían haber más en el verdadero mínimo. Hablando de eso, ese valor nunca se modifica. Luego, en cuento se encuentra una solución se devuelve... Y si hay alguna mejor por otro camino? Me está costando ver cómo se encuentra el mínimo. 
* Veo que tienen en cuenta el ordenamiento en la complejidad, pero según lo que veo en el informe el ordenamiento se hace una única vez, por lo que es algo exponencial + ordenamiento, el ordenamiento se desprecia. Igualmente, es posible que haya algo erroneo y esté basado en lo que veo del punto anterior (quiero decir, tal vez ese no es el código correcto).
* En vez de mostrar tablas para comparar tamaños de soluciones, sería mejor usar gráficos (para mostrar con muchos casos y mostrar la tendencia).
* Eso mismo vale para el caso del algoritmo greedy. 

Dicho esto, lo importante a corregir es lo que marco de la demostración. Aparte, les pido si me pueden explicar mejor dónde es que el algoritmo de Backtracking busca la solución óptima, si es que el código mostrado es el correcto o yo me estoy perdiendo dee algo. 
Las demás correcciones son opcionales.

**Comment by cmtFIUBA** [comment]
Buenas!  La función donde encuentra el mínimo n es: "solution_by_backtracking(data : ProblemData)". Ahí va actualizando los valores del n_minimo, y de hecho, nunca usa el valor default = 100. Arranca con la longitud de la lista de periodistas y va reduciendo el n con una busqueda binaria. Pusimos la función backtracking_recursivo en el informe porque es donde sucede el backtracking. Va probando soluciones y descartando caminos.

Respecto de la complejidad, esto mismo se explica en el informe. Por eso, en la página 7, concluímos que es O(N!logN), que es la complejidad de hallar una solucion para un n particular, multiplicado por la complejidad de la busqueda binaria. Ya que en el peor de los casos se repite logN veces. Lo del ordenamiento no entendí bien la corrección, ya que en el informe sucede exactamente esto que describís: se suma el ordenamiento y luego se desprecia.

**Comment by mbuchwald** [comment]
Ahí entendí. Listo. Bueno, eso explica por qué les demora. Obviamente lo de hacer una búsqueda binaria va a funcionar, pero va a demorar más que al buscar el mínimo y acotando a partir de mínimos ya encontrados previamente. 
Dicho eso, la demostración ya quedó bien (próxima porfa, pónganlo en un anexo de correcciones, así sé puntualmente qué se corrigió, o pongan un anexo indicando, o algo). 
Cerrando el tema, la nota final del tp es 8. Saludos!

**Comment by astrocinco** [comment]
Entendido. Lo ponemos en el anexo la próxima
Muchas gracias!
Que esté bien, saludos.
